/** Auto-generated by web/scripts/generate-i18n-data.mjs — do not edit manually */
import { normalizePath } from "@/lib/content/paths";
import type { Locale } from "./routing";

export type RoutePair = {
  he: string;
  en: string;
  contentId: string;
};

export const ROUTE_PAIRS: RoutePair[] = [
  {
    "he": "/",
    "en": "/en/",
    "contentId": "home"
  },
  {
    "he": "/מחירון-שיווק-דיגיטלי/",
    "en": "/en/digital-marketing-pricing/",
    "contentId": "page-22806"
  },
  {
    "he": "/website-building/",
    "en": "/en/website-building/",
    "contentId": "page-22113"
  },
  {
    "he": "/seo/",
    "en": "/en/seo/",
    "contentId": "page-22078"
  },
  {
    "he": "/google-ads/",
    "en": "/en/google-ads/",
    "contentId": "page-22011"
  },
  {
    "he": "/social-media-management/",
    "en": "/en/social-media-management/",
    "contentId": "page-22151"
  },
  {
    "he": "/check-fit/",
    "en": "/en/check-fit/",
    "contentId": "page-22694"
  },
  {
    "he": "/contact-us/",
    "en": "/en/contact-us/",
    "contentId": "page-7969"
  },
  {
    "he": "/about-us/",
    "en": "/en/about-us/",
    "contentId": "page-92"
  },
  {
    "he": "/שירותי-שיווק-דיגיטלי/",
    "en": "/en/digital-marketing-services/",
    "contentId": "page-22065"
  },
  {
    "he": "/blog/",
    "en": "/en/blog/",
    "contentId": "page-20464"
  },
  {
    "he": "/terms-of-use/",
    "en": "/en/terms-of-use/",
    "contentId": "page-2385"
  },
  {
    "he": "/privacy-policy/",
    "en": "/en/privacy-policy/",
    "contentId": "page-2383"
  },
  {
    "he": "/accessibility-statement/",
    "en": "/en/accessibility-statement/",
    "contentId": "page-20330"
  },
  {
    "he": "/thank-you-page/",
    "en": "/en/thank-you-page/",
    "contentId": "page-9103"
  },
  {
    "he": "/hosting-plans/",
    "en": "/en/hosting-plans/",
    "contentId": "page-173"
  },
  {
    "he": "/digital-marketing/websites/",
    "en": "/en/digital-marketing/websites/",
    "contentId": "category-226"
  },
  {
    "he": "/digital-marketing/google/",
    "en": "/en/digital-marketing/google/",
    "contentId": "category-227"
  },
  {
    "he": "/digital-agency/",
    "en": "/en/digital-agency/",
    "contentId": "category-232"
  },
  {
    "he": "/digital-marketing/facebook/",
    "en": "/en/digital-marketing/facebook/",
    "contentId": "category-228"
  },
  {
    "he": "/digital-marketing/internet-advertisement/",
    "en": "/en/digital-marketing/internet-advertisement/",
    "contentId": "category-230"
  },
  {
    "he": "/digital-marketing/seo/",
    "en": "/en/digital-marketing/seo/",
    "contentId": "category-412"
  },
  {
    "he": "/digital-marketing/ads/",
    "en": "/en/digital-marketing/ads/",
    "contentId": "category-229"
  },
  {
    "he": "/digital-marketing/online-marketing/",
    "en": "/en/digital-marketing/online-marketing/",
    "contentId": "category-231"
  },
  {
    "he": "/digital-marketing/",
    "en": "/en/digital-marketing/",
    "contentId": "category-1"
  },
  {
    "he": "/בדיקת-מהירות-אתר/",
    "en": "/en/website-speed-test/",
    "contentId": "post-21496"
  },
  {
    "he": "/מחשבון-roi-מעודכן-2026/",
    "en": "/en/roi-calculator-2026/",
    "contentId": "post-22727"
  },
  {
    "he": "/seo-2026-ai-answers/",
    "en": "/en/seo-2026-ai-answers/",
    "contentId": "post-22368"
  },
  {
    "he": "/שיפור-מהירות-אתר-2026-pagespeed/",
    "en": "/en/website-speed-optimization-2026-pagespeed/",
    "contentId": "post-22310"
  },
  {
    "he": "/ביקורות-גוגל-לא-עובד-❌-זו-הסיבה-למה/",
    "en": "/en/google-reviews-not-working/",
    "contentId": "post-20230"
  },
  {
    "he": "/קידום-ממומן-מול-קידום-אורגני/",
    "en": "/en/paid-vs-organic-seo/",
    "contentId": "post-21860"
  },
  {
    "he": "/מחיר-קידום-אתרים/",
    "en": "/en/seo-pricing-guide/",
    "contentId": "post-21161"
  },
  {
    "he": "/עתיד-ה-seo-כך-ייראה-הקידום-האורגני-ב-2025-ומעב/",
    "en": "/en/future-of-seo-2025/",
    "contentId": "post-21817"
  },
  {
    "he": "/אסטרטגיות-שיווק-דיגיטלי-2025/",
    "en": "/en/digital-marketing-strategies-2025/",
    "contentId": "post-21776"
  },
  {
    "he": "/כמה-עולה-לבנות-אתר-אינטרנט-בוורדפרס/",
    "en": "/en/wordpress-website-cost/",
    "contentId": "post-19792"
  },
  {
    "he": "/כך-בוחרים-חברה-לשיווק-דיגיטלי/",
    "en": "/en/choosing-digital-marketing-agency/",
    "contentId": "post-21716"
  },
  {
    "he": "/כמה-עולה-פרסום-בגוגל/",
    "en": "/en/google-ads-cost/",
    "contentId": "post-21638"
  },
  {
    "he": "/שיווק-בפייסבוק-ואינסטגרם/",
    "en": "/en/facebook-instagram-marketing/",
    "contentId": "post-21578"
  },
  {
    "he": "/google-shopping-guide/",
    "en": "/en/google-shopping-guide/",
    "contentId": "post-17923"
  },
  {
    "he": "/החיפושים-הכי-פופולריים-בגוגל-היום-ביש/",
    "en": "/en/popular-google-searches-israel/",
    "contentId": "post-10983"
  },
  {
    "he": "/סוכנות-פרסום-שיווק-בכרמיאל/",
    "en": "/en/digital-marketing-agency-carmiel/",
    "contentId": "post-21392"
  },
  {
    "he": "/רימרקטינג-מה-זה-איך-ולמה/",
    "en": "/en/remarketing-guide/",
    "contentId": "post-21272"
  },
  {
    "he": "/מהו-aeo-האם-יחליף-את-seo/",
    "en": "/en/what-is-aeo/",
    "contentId": "post-21339"
  },
  {
    "he": "/פלטפורמה-בניית-אתר/",
    "en": "/en/website-platform-guide/",
    "contentId": "post-21317"
  },
  {
    "he": "/פרסום-ממומן-בפייסבוק/",
    "en": "/en/facebook-ads-guide/",
    "contentId": "post-21249"
  },
  {
    "he": "/כמה-עולה-לבנות-אתר-מחירון-מחשבון/",
    "en": "/en/website-building-pricing/",
    "contentId": "post-21189"
  },
  {
    "he": "/קידום-אתרים-מדריך-למתחילים/",
    "en": "/en/seo-guide-for-beginners/",
    "contentId": "post-21115"
  },
  {
    "he": "/שיווק-דיגיטלי-לעסקים/",
    "en": "/en/digital-marketing-for-business/",
    "contentId": "post-21068"
  },
  {
    "he": "/מהו-שיווק-באינטרנט/",
    "en": "/en/what-is-internet-marketing/",
    "contentId": "post-21051"
  },
  {
    "he": "/פרסום-עסק-חינם/",
    "en": "/en/free-business-advertising/",
    "contentId": "post-20969"
  },
  {
    "he": "/פרסום-בגוגל-אדס-10-שלבים-פשוטים/",
    "en": "/en/google-ads-10-steps/",
    "contentId": "post-20919"
  },
  {
    "he": "/פרסום-בגוגל-7-אסטרטגיות/",
    "en": "/en/google-ads-7-strategies/",
    "contentId": "post-20897"
  },
  {
    "he": "/חברה-לשיווק-דיגיטלי/",
    "en": "/en/digital-marketing-company/",
    "contentId": "post-20803"
  },
  {
    "he": "/מה-ההבדל-בין-sem-ל-ppc/",
    "en": "/en/sem-vs-ppc/",
    "contentId": "post-20529"
  },
  {
    "he": "/סוכנות-לשיווק-דיגיטלי/",
    "en": "/en/digital-marketing-agency/",
    "contentId": "post-20506"
  },
  {
    "he": "/סוכנות-שיווק-דיגיטלי/",
    "en": "/en/digital-marketing-agency-leadership/",
    "contentId": "post-20403"
  },
  {
    "he": "/שיווק-מקצועי-לקהל-דובר-רוסית/",
    "en": "/en/russian-speaking-audience-marketing/",
    "contentId": "post-20388"
  },
  {
    "he": "/פרסום-דיגיטלי-בשפה-הרוסית/",
    "en": "/en/russian-language-digital-advertising/",
    "contentId": "post-20350"
  },
  {
    "he": "/פרסום-בגוגל-מפות/",
    "en": "/en/google-maps-advertising/",
    "contentId": "post-20155"
  },
  {
    "he": "/google-business-profile/",
    "en": "/en/google-business-profile/",
    "contentId": "post-14288"
  },
  {
    "he": "/יועץ-דיגיטל-הוא-השותף-שלך-להצלחה/",
    "en": "/en/digital-consultant-partner/",
    "contentId": "post-20092"
  },
  {
    "he": "/יועץ-שיווק-באינטרנט/",
    "en": "/en/internet-marketing-consultant/",
    "contentId": "post-20081"
  },
  {
    "he": "/ניהול-עסק-בעידן-הדיגיטלי/",
    "en": "/en/managing-business-digital-age/",
    "contentId": "post-20051"
  },
  {
    "he": "/יועץ-אינטרנט/",
    "en": "/en/internet-consultant/",
    "contentId": "post-20029"
  },
  {
    "he": "/אחסון-אתרים-מנוהל/",
    "en": "/en/managed-website-hosting/",
    "contentId": "post-19933"
  },
  {
    "he": "/כמה-עולים-שירותי-אחסון-ותחזוקת-אתרים/",
    "en": "/en/hosting-maintenance-cost/",
    "contentId": "post-19781"
  },
  {
    "he": "/אחסון-ותחזוקת-אתרים-המדריך/",
    "en": "/en/hosting-maintenance-guide/",
    "contentId": "post-19758"
  },
  {
    "he": "/אחסון-אתרי-וורדפרס-ותחזוקתם/",
    "en": "/en/wordpress-hosting-maintenance/",
    "contentId": "post-19644"
  },
  {
    "he": "/אחסון-ותחזוקת-אתרים-למה-זה-חשוב/",
    "en": "/en/why-hosting-maintenance-matters/",
    "contentId": "post-19548"
  },
  {
    "he": "/קידום-אתרים-בגוגל/",
    "en": "/en/google-seo/",
    "contentId": "post-19428"
  },
  {
    "he": "/השקעה-בפרסום-גם-בזמנים-קשים/",
    "en": "/en/advertising-investment-tough-times/",
    "contentId": "post-19398"
  },
  {
    "he": "/החשיבות-של-משרד-פרסום-דיגיטלי/",
    "en": "/en/digital-advertising-agency-importance/",
    "contentId": "post-19281"
  },
  {
    "he": "/מהי-סוכנות-דיגיטלית/",
    "en": "/en/what-is-digital-agency/",
    "contentId": "post-19143"
  },
  {
    "he": "/מדריך-קידום-העסק-בגוגל/",
    "en": "/en/google-business-promotion-guide/",
    "contentId": "post-19121"
  },
  {
    "he": "/צמיחה-עסקית-באמצעות-קידום-באינטרנט/",
    "en": "/en/business-growth-through-seo/",
    "contentId": "post-19100"
  },
  {
    "he": "/פרסום-לעסקים/",
    "en": "/en/business-advertising/",
    "contentId": "post-19070"
  },
  {
    "he": "/סוכנות-שיווק-דיגיטלית/",
    "en": "/en/digital-marketing-agency-maximize/",
    "contentId": "post-18480"
  },
  {
    "he": "/כוחם-של-ביקורות-והמלצות/",
    "en": "/en/power-of-reviews/",
    "contentId": "post-10373"
  },
  {
    "he": "/משרד-פרסום-דיגיטלי/",
    "en": "/en/digital-advertising-office/",
    "contentId": "post-10369"
  },
  {
    "he": "/blog/page/2/",
    "en": "/en/blog/page/2/",
    "contentId": "blog-page-2"
  },
  {
    "he": "/blog/page/3/",
    "en": "/en/blog/page/3/",
    "contentId": "blog-page-3"
  },
  {
    "he": "/blog/page/4/",
    "en": "/en/blog/page/4/",
    "contentId": "blog-page-4"
  },
  {
    "he": "/blog/page/5/",
    "en": "/en/blog/page/5/",
    "contentId": "blog-page-5"
  },
  {
    "he": "/blog/page/6/",
    "en": "/en/blog/page/6/",
    "contentId": "blog-page-6"
  },
  {
    "he": "/digital-marketing/websites/page/2/",
    "en": "/en/digital-marketing/websites/page/2/",
    "contentId": "category-226-page-2"
  },
  {
    "he": "/digital-marketing/websites/page/3/",
    "en": "/en/digital-marketing/websites/page/3/",
    "contentId": "category-226-page-3"
  },
  {
    "he": "/digital-marketing/google/page/2/",
    "en": "/en/digital-marketing/google/page/2/",
    "contentId": "category-227-page-2"
  },
  {
    "he": "/digital-marketing/google/page/3/",
    "en": "/en/digital-marketing/google/page/3/",
    "contentId": "category-227-page-3"
  },
  {
    "he": "/digital-marketing/google/page/4/",
    "en": "/en/digital-marketing/google/page/4/",
    "contentId": "category-227-page-4"
  },
  {
    "he": "/digital-agency/page/2/",
    "en": "/en/digital-agency/page/2/",
    "contentId": "category-232-page-2"
  },
  {
    "he": "/digital-agency/page/3/",
    "en": "/en/digital-agency/page/3/",
    "contentId": "category-232-page-3"
  },
  {
    "he": "/digital-agency/page/4/",
    "en": "/en/digital-agency/page/4/",
    "contentId": "category-232-page-4"
  },
  {
    "he": "/digital-agency/page/5/",
    "en": "/en/digital-agency/page/5/",
    "contentId": "category-232-page-5"
  },
  {
    "he": "/digital-marketing/facebook/page/2/",
    "en": "/en/digital-marketing/facebook/page/2/",
    "contentId": "category-228-page-2"
  },
  {
    "he": "/digital-marketing/facebook/page/3/",
    "en": "/en/digital-marketing/facebook/page/3/",
    "contentId": "category-228-page-3"
  },
  {
    "he": "/digital-marketing/internet-advertisement/page/2/",
    "en": "/en/digital-marketing/internet-advertisement/page/2/",
    "contentId": "category-230-page-2"
  },
  {
    "he": "/digital-marketing/internet-advertisement/page/3/",
    "en": "/en/digital-marketing/internet-advertisement/page/3/",
    "contentId": "category-230-page-3"
  },
  {
    "he": "/digital-marketing/internet-advertisement/page/4/",
    "en": "/en/digital-marketing/internet-advertisement/page/4/",
    "contentId": "category-230-page-4"
  },
  {
    "he": "/digital-marketing/ads/page/2/",
    "en": "/en/digital-marketing/ads/page/2/",
    "contentId": "category-229-page-2"
  },
  {
    "he": "/digital-marketing/ads/page/3/",
    "en": "/en/digital-marketing/ads/page/3/",
    "contentId": "category-229-page-3"
  },
  {
    "he": "/digital-marketing/ads/page/4/",
    "en": "/en/digital-marketing/ads/page/4/",
    "contentId": "category-229-page-4"
  },
  {
    "he": "/digital-marketing/online-marketing/page/2/",
    "en": "/en/digital-marketing/online-marketing/page/2/",
    "contentId": "category-231-page-2"
  },
  {
    "he": "/digital-marketing/online-marketing/page/3/",
    "en": "/en/digital-marketing/online-marketing/page/3/",
    "contentId": "category-231-page-3"
  },
  {
    "he": "/digital-marketing/online-marketing/page/4/",
    "en": "/en/digital-marketing/online-marketing/page/4/",
    "contentId": "category-231-page-4"
  },
  {
    "he": "/digital-marketing/page/2/",
    "en": "/en/digital-marketing/page/2/",
    "contentId": "category-1-page-2"
  },
  {
    "he": "/digital-marketing/page/3/",
    "en": "/en/digital-marketing/page/3/",
    "contentId": "category-1-page-3"
  },
  {
    "he": "/digital-marketing/page/4/",
    "en": "/en/digital-marketing/page/4/",
    "contentId": "category-1-page-4"
  },
  {
    "he": "/digital-marketing/page/5/",
    "en": "/en/digital-marketing/page/5/",
    "contentId": "category-1-page-5"
  },
  {
    "he": "/digital-marketing/page/6/",
    "en": "/en/digital-marketing/page/6/",
    "contentId": "category-1-page-6"
  }
];

const heToEn = new Map(ROUTE_PAIRS.map((p) => [p.he, p.en]));
const enToHe = new Map(ROUTE_PAIRS.map((p) => [p.en, p.he]));
const enToContentId = new Map(ROUTE_PAIRS.map((p) => [p.en, p.contentId]));
const heToContentId = new Map(ROUTE_PAIRS.map((p) => [p.he, p.contentId]));

export function getContentId(path: string, locale: Locale): string | undefined {
  const key = normalizePath(path);
  return locale === "en" ? enToContentId.get(key) : heToContentId.get(key);
}

export function pathForLocale(path: string, locale: Locale): string {
  const key = normalizePath(path);
  if (locale === "en") {
    return heToEn.get(key) ?? (key === "/" ? "/en/" : key.startsWith("/en/") ? key : normalizePath(`/en${key}`));
  }
  if (key.startsWith("/en/")) {
    return enToHe.get(key) ?? "/";
  }
  return key;
}

export function alternatePaths(path: string): { he: string; en: string } | null {
  const key = normalizePath(path);
  if (heToEn.has(key)) {
    return { he: key, en: heToEn.get(key)! };
  }
  if (enToHe.has(key)) {
    return { he: enToHe.get(key)!, en: key };
  }
  return null;
}

export function localizedHref(path: string, locale: Locale): string {
  return pathForLocale(path, locale);
}
